---
- hosts: all
  tasks:
    - name: "User > Add groups"
      group:
        name: "{{ group }}"
        state: present

    - name: "User > Add users"
      user:
        name: "{{ users }}"
        state: "{{ state }}"
        group: "{{ group }}"
